version: '3'


services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  pgdata:

