version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    networks:
      - db-net
    depends_on:
      - db
      - nats
    env_file:
      - ./.env
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - db-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db-migrate:
    container_name: db-migrate
    image: migrate/migrate
    networks:
      - db-net
    depends_on:
      - db
    volumes:
      - ./schema:/schema
    command: [
      "-path",
      "/schema",
      "-database",
      "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}",
      "up"
    ]
    links:
      - db
  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - db-net
    restart: always
    command: [
      "-p",
      "4222",
      "-hbi",
      "5s",
      "-hbt",
      "5s",
      "-hbf",
      "2",
      "-SD",
      "-cid",
      "simple-cluster",
      "-m",
      "8222"
    ]


networks:
  db-net:

volumes:
  pgdata:
