version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    networks:
      - db-net
    depends_on:
      - db
      - nats
    env_file:
      - ./.env
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - db-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db-migrate:
    container_name: db-migrate
    image: migrate/migrate
    networks:
      - db-net
    depends_on:
      - db
    volumes:
      - ./schema:/schema
    command: [
      "-path",
      "/schema",
      "-database",
      "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${SSL_MODE}",
      "up"
    ]
    links:
      - db
  nats:
    image: nats-streaming:latest
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - "./data:/data"
    env_file:
      - ./.env
    environment:
      - NATS_STREAMING_CLUSTER_ID
      - NATS_STREAMING_STORE_TYPE
      - NATS_USER
      - NATS_PASSWORD
networks:
  db-net:
volumes:
  pgdata:


